### ISSUE TITLE
Undefined index and other PHP warnings

### ISSUE THREAD

**Issue by ablears** [RemitaNet/remita-woocommerce#1]
Using PHP 7.3 FPM, I see the following error logs related to this plugin (v1.0).

> Undefined index: remita_title in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 69

> Undefined index: remita_description in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 70

> Undefined index: remita_publickey in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 71

> Undefined index: remita_secretkey in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 72

> Undefined index: remita_mode in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 73

> Undefined index: remita_checkout_method in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 74

> Undefined index: thanks_message in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 75

> Undefined index: error_message in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 76

> Undefined index: order in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 383

> Trying to get property 'order_total' of non-object in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 385

> Trying to get property 'billing_email' of non-object in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 387

> Trying to get property 'billing_phone' of non-object in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 388

> Trying to get property 'billing_first_name' of non-object in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 389

> Trying to get property 'billing_last_name' of non-object in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 390

> Undefined variable: jsFile in /var/redacted/wp-content/plugins/remita-payment-gateway/woocommerce_remita.php on line 403

**Comment by favourmark05** [comment]
Hello @ablears ,

Thank you for bringing this to our attention! We've addressed the issue, and the error has been fixed in the latest update. We're committed to maintaining the plugin and ensuring its functionality for all users. Feel free to give it another try!
